### PR TITLE
fix: error in archive file matching functionality for sdists

### LINKED ISSUE #132: Wheel building is not doing anything for `ruff`
# Description

When running:

```bash
cargo r ruff --install-into /tmp/ruff --only-sdists
```

We get the following output when installing:

```
<snip solving>

installing: ruff - 0.1.9
2023-12-22T12:24:49.133085Z  INFO rattler_installs_packages::index::http: executing request url=https://files.pythonhosted.org/packages/6d/50/a3b468c0aa5da0ba0485e250398252848cf44a1bcc930f0365e80ca1ae7a/ruff-0.1.9.tar.gz#sha256=b041dee2734719ddbb4518f762c982f2e912e7f28b8ee4fe1dee0b15d1b6e800 cache_mode=Default
2023-12-22T12:24:49.220619Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::wheel_builder::build_environment: build requirements: ["setuptools", "wheel"]
2023-12-22T12:24:49.220661Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting setuptools
2023-12-22T12:24:49.222236Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting wheel
2023-12-22T12:24:49.225179Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: obtaining dependency information from wheel=0.42.0
2023-12-22T12:24:49.225344Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting wheel[test]
2023-12-22T12:24:49.225447Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: obtaining dependency information from setuptools=69.0.2
2023-12-22T12:24:49.225604Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting setuptools[testing]
2023-12-22T12:24:49.227359Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting setuptools[ssl]
2023-12-22T12:24:49.229052Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting setuptools[certs]
2023-12-22T12:24:49.230829Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting setuptools[testing-integration]
2023-12-22T12:24:49.232470Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::resolve::dependency_provider: collecting setuptools[docs]
2023-12-22T12:24:49.236227Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::index::http: executing request url=https://files.pythonhosted.org/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl#sha256=177f9c9b0d45c47873b619f5b650346d632cdc35fb5e4d25058e09c9e581433d cache_mode=Default
2023-12-22T12:24:49.256373Z  INFO build_wheel{name=ruff version=0.1.9}: rattler_installs_packages::index::http: executing request url=https://files.pythonhosted.org/packages/bb/e1/ed2dd0850446b8697ad28d118df885ad04140c64ace06c4bd559f7c8a94f/setuptools-69.0.2-py3-none-any.whl#sha256=1e8fdff6797d3865f37397be788a4e3cba233608e9b509382a2777d25ebde7f2 cache_mode=Default
```

This shows the build environment being setup correctly, however the `ruff` rust source code is not being built. I've verified that this works in a venv with `pip install --no-binary :all: ruff`. This seems to work perfectly on my machine, I have rust and cargo on my host.

# Solution

Unsure yet, `ruff` uses maturin as build backend. However, I do not see that coming back in the logs, maybe the parsing of the pyproject.toml is failing? I feel like the correct commands are being run for the wrong build-backend.

### PR DESCRIPTION
**Pull request by tdejager**
The wrong file could be selected searching for file 'a' in archive could also potentially find `foo/bar/a` while you were trying to find a file in the root

Fixes #132, because a wrong `pyproject.toml` file was found for the `ruff` source distribution, as we were using `ends_with` to match the path of the entry in the archive. A `pyproject.toml` from a sub-crate was selected instead of the root `pyproject.toml`.

Fixes #132, however exposes a new bug: #137.

### CODE REVIEW

**Comment by tdejager** [comment]
@baszalmstra @orhun do you know a better way to re-write the `strip_until_containing_prefix` ideally without the `PathBuf` allocation?

File: crates/rattler_installs_packages/src/artifacts/sdist.rs [hunk 1]
```diff
@@ -43,6 +44,25 @@ pub enum SDistError {
...
+    // Use up until the last occurrence of the distribution name
+    let components = path
+        .components()
+        .rev()
+        .take_while(|c| {
+            !c.as_os_str()
+                .to_str()
+                // Keep taking if we cannot convert
+                .unwrap_or("")
+                .contains(name)
```
Comment (wolfv) [inline crates/rattler_installs_packages/src/artifacts/sdist.rs:58]: `.starts_with` is not correct?

Comment (baszalmstra) [reply crates/rattler_installs_packages/src/artifacts/sdist.rs:58]: Or `==`?

File: crates/rattler_installs_packages/src/artifacts/sdist.rs [hunk 2]
```diff
@@ -43,6 +44,25 @@ pub enum SDistError {
     WheelCoreMetaDataError(#[from] WheelCoreMetaDataError),
 }
 
+/// Pop until the file name is found an use the rest of the path
```
Comment (wolfv) [inline crates/rattler_installs_packages/src/artifacts/sdist.rs:47]: If I understand the function correctly, then the description is not quite matching what it does, right? `name` -> `prefix` and maybe something like:

`Returns the remainder of the path that follows the last component that starts with "prefix". For example, `strip_until_containing_prefix("bla", "/my/blabli/path/bla/path/remainder) -> "path/remainder"`

File: crates/rattler_installs_packages/src/artifacts/sdist.rs (hunk 1 above)
Comment (tdejager) [reply crates/rattler_installs_packages/src/artifacts/sdist.rs:58]: `starts_with` would work I suppose, `==` not because `flask` should match for `flask-1.0.0` and such.

File: crates/rattler_installs_packages/src/artifacts/sdist.rs (hunk 2 above)
Comment (tdejager) [reply crates/rattler_installs_packages/src/artifacts/sdist.rs:47]: Yes that seems better!

**Comment by wolfv** [comment]
LGTM!
